### ISSUE TITLE
Incorrect capitalisation in New-RandomExcuse output

### ISSUE THREAD

**Issue by SP3269** [DBHeise/RoboDave#2]
This is rather simple issue: New-RandomExcuse generates blank line, followed by address starting with lower case word:
```
oh scintillating princess,
    Sorry, but I cannot grow the hole because I am currently explaining the rightful tofu.
Sincerely,
   Your drunk brother.

```
Expected behaviour: the address starts with a capital letter, no blank lines:
```
Oh scintillating princess,
    Sorry, but I cannot grow the hole because I am currently explaining the rightful tofu.
Sincerely,
   Your drunk brother.
```

**Comment by DBHeise** [comment]
Fixed by adding string post-modifiers to the madlib generation engine.
